name: ğŸª„ Code Embedder

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  code_embedder:
    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: "{{ cookiecutter.minimal_python_version }}"
    steps:
      - name: ğŸ›ï¸ Checkout
        uses: actions/checkout@v4

      - name: ğŸ Install uv with caching
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
          version: "0.5.4"

    {%- raw %}
      - name: ğŸ Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
    {%- endraw %}

      - name: ğŸ’¾ Setup pip cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          {%- raw %}
          key: ${{ runner.os }}-pip-${{ hashFiles('uv.lock') }}
          {%- endraw %}

      - name: ğŸ“¥ Install the project
        run: |
          uv sync --all-extras --dev
          uv pip install .

      - name: ğŸª„ Format raw code snippets with ruff
        run: |
          pipx install ruff
          ruff format dev/readme_snippets/

      - name: ğŸª„ Format print comments in code snippets
        run: python dev/scripts/format_snippet_prints.py

      - name: ğŸ“ Run code embedder
        uses: kvankova/code-embedder@v1.1.1
        env:
          {%- raw %}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          {%- endraw %}
